"""Phase 5 migration protocol exports."""

from .core import (
    build_modules_from_overview,
    build_phases_from_overview,
    create_new_execution_guide,
    freeze_all_old_active_attempts,
    freeze_all_old_active_guides,
    freeze_old_active_runtime,
    handle_module_mapping,
    handle_phase_mapping,
    has_active_attempt_conflict,
    has_complete_mapping,
    has_unresolved_structural_violation,
    inherit_allowed_runtime_context,
    mark_old_objects_superseded_or_obsolete,
    migrate_overview,
    recompute_module_state,
    relink_historical_action_records,
    resolve_resume_module,
    resolve_resume_phase,
)
from .models import (
    MigrationDecision,
    MigrationItemResult,
    MigrationMappingType,
    MigrationOutcomeKind,
    MigrationRunResult,
    MigrationStatus,
    ModuleMigrationItem,
    OverviewMigration,
    PhaseMigrationItem,
    StateInheritanceMode,
)

__all__ = [
    "MigrationDecision",
    "MigrationItemResult",
    "MigrationMappingType",
    "MigrationOutcomeKind",
    "MigrationRunResult",
    "MigrationStatus",
    "ModuleMigrationItem",
    "OverviewMigration",
    "PhaseMigrationItem",
    "StateInheritanceMode",
    "build_modules_from_overview",
    "build_phases_from_overview",
    "create_new_execution_guide",
    "freeze_all_old_active_attempts",
    "freeze_all_old_active_guides",
    "freeze_old_active_runtime",
    "handle_module_mapping",
    "handle_phase_mapping",
    "has_active_attempt_conflict",
    "has_complete_mapping",
    "has_unresolved_structural_violation",
    "inherit_allowed_runtime_context",
    "mark_old_objects_superseded_or_obsolete",
    "migrate_overview",
    "recompute_module_state",
    "relink_historical_action_records",
    "resolve_resume_module",
    "resolve_resume_phase",
]
